name: regenerate

on:
  push:

jobs:
  regenerate_dist-index_js:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2.3.4
    - 
      name: regenerate dist/index.js
      run: |
        sudo npm i -g @vercel/ncc@0.26.2
        npm install
        ncc build index.js
    -
      name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@2fde6fc18d3b24c2561ba4b73a8e015e863cef85
      with:
        file_pattern: dist/index.js
        commit_message: Regenerate dist/index.js
        
        
